name: Update gist with WakaTime stats
on:
  schedule:
      - cron: "0 */2 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        run: node ./dist/index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 7f8d2b8e037800b2449c0d273c1c559f
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
